require("dotenv").config({ path: require("path").join(__dirname, ".env") });

module.exports = {
  apps: [
    {
      name: "myrankapp",
      cwd: "/root/myrankapp",
      script: "index.js",
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      watch: false,
      max_memory_restart: "512M",
      min_uptime: "10s",
      max_restarts: 10,
      env: {
        NODE_ENV: "production",
        PORT: 3000,
        GRPC_DNS_RESOLVER: "ares",
        API_TIMEOUT_MS: 25000,
        FIREBASE_STORAGE_BUCKET: "myrankapp-d62b9.firebasestorage.app",
        REDIS_URL: "redis://127.0.0.1:6379",
        FOLLOWING_FEED_USER_FEEDS_ONLY: "true",
        MEDIA_PROXY_ORIGIN: "https://myrank.com.tr",
        STATUS_SECRET: process.env.STATUS_SECRET || "",
      },
    },
    {
      name: "myrankapp-worker",
      cwd: "/root/myrankapp",
      script: "worker.js",
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      watch: false,
      max_memory_restart: "256M",
      min_uptime: "10s",
      max_restarts: 10,
      env: {
        NODE_ENV: "production",
        GRPC_DNS_RESOLVER: "ares",
        FIREBASE_STORAGE_BUCKET: "myrankapp-d62b9.firebasestorage.app",
        REDIS_URL: "redis://127.0.0.1:6379",
        STATUS_SECRET: process.env.STATUS_SECRET || "",
      },
    },
    {
      name: "myrankapp-staging",
      cwd: "/root/myrankapp",
      script: "index.js",
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      watch: false,
      max_memory_restart: "512M",
      min_uptime: "10s",
      max_restarts: 10,
      env: {
        NODE_ENV: "staging",
        PORT: 3001,
        GRPC_DNS_RESOLVER: "ares",
        API_TIMEOUT_MS: 25000,
        FIREBASE_STORAGE_BUCKET: "myrankapp-d62b9.firebasestorage.app",
        REDIS_URL: "redis://127.0.0.1:6379",
        FOLLOWING_FEED_USER_FEEDS_ONLY: "true",
        MEDIA_PROXY_ORIGIN: "https://staging.myrank.com.tr",
      },
    },
  ],
};
