module.exports = {
  apps: [
    {
      name: "myrankapp",
      cwd: "/root/myrankapp",
      script: "index.js",
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      watch: false,
      max_memory_restart: "512M",
      min_uptime: "10s",
      max_restarts: 10,
      env: {
        NODE_ENV: "production",
        PORT: 3000,
        GRPC_DNS_RESOLVER: "ares",
        API_TIMEOUT_MS: 25000,
        FIREBASE_STORAGE_BUCKET: "myrankapp-d62b9.firebasestorage.app",
      },
    },
    {
      name: "myrankapp-staging",
      cwd: "/root/myrankapp",
      script: "index.js",
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      watch: false,
      max_memory_restart: "512M",
      min_uptime: "10s",
      max_restarts: 10,
      env: {
        NODE_ENV: "staging",
        PORT: 3001,
        GRPC_DNS_RESOLVER: "ares",
        API_TIMEOUT_MS: 25000,
        FIREBASE_STORAGE_BUCKET: "myrankapp-d62b9.firebasestorage.app",
      },
    },
  ],
};
